In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("last element from 2nd dim:",arr[1,-1])

last element from 2nd dim: 10


In [3]:
import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1])

[2 7]


In [4]:
import numpy as np
arr =np.array([1,2,3,4])
print(arr.dtype)

int32


In [5]:
import numpy as np
arr =np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
arr1 = np.array([1,2,3,4,5])
x1 = arr.view()
arr1[0]= 42
print(arr1)
print(x1)
print(x.base)
print(x1.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [8]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array :',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2,)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
#example for 1D array
import numpy as np
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [13]:
#example for 2D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    for x in arr:
        for y in x:
            print(y)

[1 2 3]
1
2
3
4
5
6
[4 5 6]
1
2
3
4
5
6


In [14]:
# Joining numpy arrays
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [15]:
# Joining numpy arrays
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
#Joining arrays using stock functions
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
# stacking along rows
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [21]:
# stacking along columns
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
# stacking along height(depth)
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [23]:
#splitting numpy arrays
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
