In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])


In [3]:
import numpy as np
arr = np.array(42)
print(arr)
arr1 =np.array([1,2,3,4,5])
print(arr1)
arr2 =np.array([[1,2,3,],[5,5,6]])
print(arr2)
arr3 =np.array([[[1,2,3],[4,5,6]],[1,2,3],[4,5,6]])
print(arr3)
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


42
[1 2 3 4 5]
[[1 2 3]
 [5 5 6]]
[list([[1, 2, 3], [4, 5, 6]]) list([1, 2, 3]) list([4, 5, 6])]
0
1
2
1


C:\Users\Chaitra\AppData\Local\Temp\ipykernel_10928\2052988298.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 =np.array([[[1,2,3],[4,5,6]],[1,2,3],[4,5,6]])


In [5]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5
